name: Python application

on:
  push:
    branches:
      - presidio
  pull_request:
    branches:
      - presidio

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install spaCy model
      run: |
        python -m spacy download en_core_web_sm

    - name: Run black to format code
      run: |
        pip install black
        black .

    - name: Run tests
      run: |
        pytest || echo "Tests failed but continuing..."  # Optional

    - name: Start Flask server (optional)
      run: |
        nohup flask run &

    - name: Stop Flask server (optional)
      run: |
        pkill -f "flask run"  # This stops the Flask server if it was started
