name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install spaCy model
      run: |
        python -m spacy download en_core_web_sm

    - name: Run tests
      run: |
        pytest  # Run your tests if you have them; you can replace this with the actual test command if it's different

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Start Flask server (optional)
      run: |
        export FLASK_APP=app
        export FLASK_ENV=production  # or 'development' if you want to use that
        flask run --host=0.0.0.0  # You can customize this command to match your app's needs

    - name: Stop Flask server (optional)
      if: always()
      run: |
        pkill -f "flask run"  # This stops the Flask server if it was started

    - name: Archive production artifacts (optional)
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: production-files
        path: |
          app/**/*.py
          requirements.txt
